CREATE TABLE MEMBER(
mno NUMBER(4)
    CONSTRAINT MEMBER_MNO_PK PRIMARY KEY,
name VARCHAR2(15 CHAR)
    CONSTRAINT MEMBER_NAME_NN NOT NULL,
id VARCHAR2(15 CHAR)
    CONSTRAINT MEMBER_ID_UK UNIQUE
    CONSTRAINT MEMBER_ID_NN NOT NULL,
pw VARCHAR2(12 CHAR)
    CONSTRAINT MEMBER_PW_NN NOT NULL,
mail VARCHAR2(50 CHAR)
    CONSTRAINT MEMBER_MAIL_NN NOT NULL,
tel VARCHAR2 (13 CHAR)
    CONSTRAINT MEMBER_TEL_NN NOT NULL,
gen CHAR(1)
    CONSTRAINT MEMBER_GEN_NN NOT NULL
    CONSTRAINT MEMBER_GEN_CK CHECK(gen in('M', 'F')),
avt NUMBER(2) 
    CONSTRAINT MEMBER_AVT_FK FOREIGN KEY
    CONSTRAINT MEMBER_AVT_NN NOT NULL,
hiredate DATE DEFAULT sysdate
    CONSTRAINT MEMBER_DATE_NN NOT NULL,
isshow CHAR(1) DEFAULT 'N'
    CONSTRAINT MEMBER_ISSHOW_NN NOT NULL
    CONSTRAINT MEMBER_ISSHOW_CK CHECK(isshow in('Y', 'N')
);

CREATE TABLE GUEST(
gno NUMBER(4)
    CONSTRAINT GUEST_GNO_PK PRIMARY KEY,
name VARCHAR2(15 CHAR)
    CONSTRAINT GUEST_NAME_FK FOREIGN KEY
    CONSTRAINT GUEST_NAME_NN NOT NULL,
text VARCHAR2(100 CHAR)
    CONSTRAINT GUEST_TEXT_UK UNIQUE
    CONSTRAINT GUEST_TEXT_NN NOT NULL,
credate DATE  DEFAULT sysdate
    CONSTRAINT GUEST_CREDATE_NN NOT NULL
);

CREATE TABLE AVATAR(
uno NUMBER(4)
    CONSTRAINT GUEST_UNO_PK PRIMARY KEY,
gen CHAR(1)
    CONSTRAINT GUEST_GEN_NN NOT NULL
    CONSTRAINT GUEST_GEN_CK CHECK(gen in('M', 'F')),
sname VARCHAR2(15 CHAR)
    CONSTRAINT AVATAR_SNAME_NN NOT NULL,
loc VARCHAR2(50 CHAR)
    CONSTRAINT AVATAR_LOC_NN NOT NULL
);

    
    
    